-- 001_init.sql
-- Core schema for Talking Rain TPM app (initial).
-- Notes:
-- - Uses UUID primary keys (generated by the application) to work well with distributed edits.
-- - Stores audit events as append-only JSON snapshots.
-- - This schema is intentionally "master-data first" so admin modules can be built early.

-- Track applied migrations (very small homegrown migration runner)
CREATE TABLE IF NOT EXISTS schema_migrations (
  id TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- App users: we key by Entra object id (oid) so it is stable across sessions.
CREATE TABLE IF NOT EXISTS app_user (
  id UUID PRIMARY KEY,
  entra_oid TEXT UNIQUE NOT NULL,
  email TEXT,
  display_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Org hierarchy: manager -> report (both are app_user records).
CREATE TABLE IF NOT EXISTS org_reporting (
  id UUID PRIMARY KEY,
  manager_user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  report_user_id  UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (manager_user_id, report_user_id),
  CHECK (manager_user_id <> report_user_id)
);

-- Retailer / Division / Account master data.
CREATE TABLE IF NOT EXISTS retailer (
  id UUID PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS division (
  id UUID PRIMARY KEY,
  retailer_id UUID NOT NULL REFERENCES retailer(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (retailer_id, name)
);

-- Account represents a canonical key from uploads (we'll confirm exact identifier later).
CREATE TABLE IF NOT EXISTS account (
  id UUID PRIMARY KEY,
  retailer_id UUID REFERENCES retailer(id) ON DELETE SET NULL,
  external_key TEXT UNIQUE NOT NULL,
  name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Admin-managed mapping: Account -> Division (retroactive truth).
CREATE TABLE IF NOT EXISTS account_division_map (
  id UUID PRIMARY KEY,
  account_id UUID NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  division_id UUID NOT NULL REFERENCES division(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (account_id)
);

-- Promo type master list (admin-managed).
CREATE TABLE IF NOT EXISTS promo_type (
  id UUID PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Promo type applicability by retailer/division.
CREATE TABLE IF NOT EXISTS promo_type_applicability (
  id UUID PRIMARY KEY,
  retailer_id UUID NOT NULL REFERENCES retailer(id) ON DELETE CASCADE,
  division_id UUID REFERENCES division(id) ON DELETE CASCADE,
  promo_type_id UUID NOT NULL REFERENCES promo_type(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (retailer_id, division_id, promo_type_id)
);

-- Fiscal calendar configuration: supports Mon-Sun vs Sun-Sat and FY anchor.
CREATE TABLE IF NOT EXISTS fiscal_calendar_config (
  id UUID PRIMARY KEY,
  -- Week convention: 'MON' (Mon-Sun) or 'SUN' (Sun-Sat)
  week_start_day TEXT NOT NULL DEFAULT 'MON' CHECK (week_start_day IN ('MON','SUN')),
  -- Fiscal year anchor date (admin-chosen). Used only for prepopulation helpers.
  fy_anchor_date DATE,
  -- Period pattern for P1..P12. Default 4-4-5 repeated.
  period_pattern TEXT NOT NULL DEFAULT '4-4-5-4-4-5-4-4-5-4-4-5',
  -- How to handle a 53rd week: default 'P12', optionally allow 'P13'
  extra_week_default_period TEXT NOT NULL DEFAULT 'P12' CHECK (extra_week_default_period IN ('P12','P13')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fiscal weeks: source of truth for rollups. Admin can edit anytime.
CREATE TABLE IF NOT EXISTS fiscal_week (
  id UUID PRIMARY KEY,
  calendar_config_id UUID NOT NULL REFERENCES fiscal_calendar_config(id) ON DELETE CASCADE,
  week_start_date DATE NOT NULL,
  week_end_date DATE NOT NULL,
  fiscal_year INT NOT NULL,
  fiscal_period TEXT NOT NULL CHECK (fiscal_period ~ '^P([1-9]|1[0-3])$'),
  fiscal_week_of_year INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (calendar_config_id, week_start_date),
  CHECK (week_end_date >= week_start_date)
);

-- Audit log: append-only.
CREATE TABLE IF NOT EXISTS audit_log (
  id UUID PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actor_user_id UUID REFERENCES app_user(id) ON DELETE SET NULL,
  actor_entra_oid TEXT,
  actor_email TEXT,
  source TEXT NOT NULL DEFAULT 'ui' CHECK (source IN ('ui','upload','system')),
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  correlation_id TEXT,
  before JSONB,
  after JSONB,
  metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_actor  ON audit_log(actor_entra_oid);
CREATE INDEX IF NOT EXISTS idx_week_lookup  ON fiscal_week(calendar_config_id, fiscal_year, fiscal_period);
